[project]
name = "image-convert-qt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "piexif>=1.1.3",
    "pillow>=12.0.0",
    "pillow-heif>=1.1.1",
    "pyside6>=6.10.0",
]
